spring.datasource.url=jdbc:mysql://localhost:3306/servicemate
spring.datasource.username=root
spring.datasource.password=Sanjay@433
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Important: Use 'validate' once you've run the SQL script
# Update the dialect to the modern version


# Change validate to update temporarily to let Hibernate fix minor issues
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect